### ISSUE TITLE
android 4.2.2上无法响应点击事件  5.1可以 

### ISSUE THREAD

**Issue by fluttergo** [liaohuqiu/android-UCToast#2]

**Comment by WonShaw** [comment]
我把原文更新了, 增加了对UC浏览器分版本处理的逆向分析

http://www.jianshu.com/p/167fd5f47d5c

**Comment by liaohuqiu** [comment]
What kind of OS you are using?  I think I've fixed it now. Could test it for me? Thank you in advance.

你的是什么系统？你尝试 fix 了，在模拟器上正常，你可以帮我测试一下，看看搞定了吗？
